(global-set-key (kbd "<f7>") 'xah-new-empty-buffer)
(global-set-key (kbd "C-!") 'eshell-here)
(global-set-key (kbd "<C-return>") 'xah-run-current-file)
(global-set-key (kbd "<C-;>") 'cjhao/insert-semicolon-to-the-end-of-current-line)
(define-key global-map (kbd "C-c y") 'youdao-dictionary-search-at-point+)